### ISSUE TITLE
minisign 0.10 signature verification broken

### ISSUE THREAD

**Issue by infraweavers** [jedisct1/go-minisign#8]
Using the latest version of go-minisign, it is not possible to verify signatures created with minisign 0.10 - output is "Incompatible signature algorithm".  minisign 0.9 signatures can be successfully verified, as can 0.10 signatures when signed with the 'legacy' option.  Have tried generating a new keypair with 0.10 but that doesn't make any difference.

**Comment by harshavardhana** [comment]
This also broke https://github.com/minio/minio binary verification - thanks for the fix @jedisct1
